[build]
  command = "mv books/* website/static/ && cd website && hugo --gc --minify"
  publish = "website/public"

[build.environment]
  HUGO_VERSION = "0.69.0"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"
